### ISSUE TITLE
The material is blurred

### ISSUE THREAD

**Issue by Mamubai** [Ryan-DowlingSoka/ReliefMappingWiki#1]
The plugin is very useful, but the material I made was blurry
![Uploading HighresScreenshot00001.png…]()

**Comment by Ryan-DowlingSoka** [comment]
Hi, the screenshot doesn't appear to be working for me. Perhaps try uploading it a different way?

**Comment by Mamubai** [comment]
Hello, the material I made with the utility plugin is blurry, and that's why




未来在手中
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Ryan-DowlingSoka/ReliefMappingWiki"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年7月15日(星期一) 上午8:18
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [Ryan-DowlingSoka/ReliefMappingWiki] The material is blurred (Issue #1)





 
Hi, the screenshot doesn't appear to be working for me. Perhaps try uploading it a different way?

**Comment by Ryan-DowlingSoka** [comment]
Hi, I need to see your material, and your results to be able to help.

**Comment by Mamubai** [comment]
Is there anything else I need to offer ...




未来在手中
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Ryan-DowlingSoka/ReliefMappingWiki"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年7月17日(星期三) 中午11:38
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [Ryan-DowlingSoka/ReliefMappingWiki] The material is blurred (Issue #1)





 
Hi, I need to see your material, and your results to be able to help.

**Comment by Ryan-DowlingSoka** [comment]
Yeah, I need:

Screenshots of your blurry material.

Please respond with pictures on GitHub directly, I do not think email works to include screenshots.

**Comment by Ryan-DowlingSoka** [comment]
Your original screenshot didn't work.  It looks like this:

![Screenshot_20240716_204559_Chrome](https://github.com/user-attachments/assets/ac8759e6-e4bf-4e70-a59d-28c86e10c292)

**Comment by Mamubai** [comment]
![HighresScreenshot00001](https://github.com/user-attachments/assets/7f1e6f31-76eb-40f3-9b57-c6bd28708d57)
![QQ截图20240717114055](https://github.com/user-attachments/assets/ac33a03f-1536-468c-835c-9a26dad11eb6)

![Uploading QQ截图20240717114137.png…]()

**Comment by Mamubai** [comment]
![Uploading QQ截图20240717113949.png…]()

**Comment by Mamubai** [comment]
![QQ截图20240717114137](https://github.com/user-attachments/assets/f04ebe49-86d4-4719-9721-c128f2d03981)

**Comment by Mamubai** [comment]
![QQ截图20240717113949](https://github.com/user-attachments/assets/b238b38d-2ddb-4006-998a-c9da89d3c7b5)

**Comment by Mamubai** [comment]
Can you see it now, please

**Comment by Ryan-DowlingSoka** [comment]
I expect this may be because your are using virtual texture streaming. 

You may be able to fix this by using explicit derivatives in your texture samplers and/or swapping the texture samplers to use virtual textures.

Select each texture node in the material and switch to the corresponding sampler mode to be virtual texture modes. 

Alternatively, turn off virtual texture streaming for your textures and see if that helps.

**Comment by Mamubai** [comment]
Can the operation be more specific, can you provide an example of an image?

**Comment by Ryan-DowlingSoka** [comment]
I am in vacation. I will send screenshots in a few days.

**Comment by Mamubai** [comment]
Okay,

**Comment by Ryan-DowlingSoka** [comment]
There are 3 solutions. Pick the one you feel works best for you:

----

Option 1) Open each texture in the material, and set `Enable Virtual Texture Streaming` to `False`
![image](https://github.com/user-attachments/assets/867f4c07-6e60-4bc5-b2aa-ae909bbe7c3f)

----

Option 2) Disable Virtual Texture Streaming support in the project settings.
<img width="977" alt="image" src="https://github.com/user-attachments/assets/3bfeb794-4893-4768-92ea-6e41b5672252">

----

Option 3) Switch to using virtual textures for the texture samplers. To do so, go into the material, and for the `Albedo`, `Metalness`, `ARD`, `Normal` : replace each with the matching VT version.

For albedo there is an existing VT version.
<img width="847" alt="image" src="https://github.com/user-attachments/assets/87db9d99-5c75-4d1a-a928-96b68fc49b44">

For Metallic, ARD, and Normal there is not so use the conversion tool to convert them to VT.
![image](https://github.com/user-attachments/assets/138b6a9a-c295-4158-810a-244e2e0e075d)

Set the texture size filter to 1
![image](https://github.com/user-attachments/assets/a744f2b2-2179-423a-88d7-e4093dd7f925)

The Relief Map Texture cannot be a Virtual Texture. So set the RCSM to a different black texture. 
![image](https://github.com/user-attachments/assets/ade8f412-e914-4d40-9199-e5fc4c19378f)

Before:
![image](https://github.com/user-attachments/assets/deba218a-cb0c-4f92-828d-eeaf953b9770)

After:
![image](https://github.com/user-attachments/assets/963a4d30-b655-4d65-a7d6-a48564ab452c)

**Comment by Mamubai** [comment]
Thank you very much, it's been resolved




未来在手中
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Ryan-DowlingSoka/ReliefMappingWiki"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年7月18日(星期四) 中午1:06
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [Ryan-DowlingSoka/ReliefMappingWiki] The material is blurred (Issue #1)





 
There are 3 solutions. Pick the one you feel works best for you:
 
 
Option 1) Open each texture in the material, and set Enable Virtual Texture Streaming to False
 image.png (view on web)
 
 
Option 2) Disable Virtual Texture Streaming support in the project settings.
 image.png (view on web)
 
 
Option 3) Switch to using virtual textures for the texture samplers. To do so, go into the material, and for the Albedo, Metalness, ARD, Normal : replace each with the matching VT version.
 
For albedo there is an existing VT version.
 image.png (view on web)
 
For Metallic, ARD, and Normal there is not so use the conversion tool to convert them to VT.
 image.png (view on web)
 
Set the texture size filter to 1
 image.png (view on web)
 
The Relief Map Texture cannot be a Virtual Texture. So set the RCSM to a different black texture.
 image.png (view on web)
 
Before:
 image.png (view on web)
 
After:
 image.png (view on web)

**Comment by Mamubai** [comment]
Hello, there are some shadows on the screen
![Uploading HighresScreenshot00002.png…]()

**Comment by Ryan-DowlingSoka** [comment]
Your screenshot did not work again.

**Comment by Mamubai** [comment]
![Uploading HighresScreenshot00002.png…]()

**Comment by Mamubai** [comment]
![HighresScreenshot00002](https://github.com/user-attachments/assets/42029dc4-07ee-4a87-b2ce-7f474298e335)

**Comment by Ryan-DowlingSoka** [comment]
If you are using the Pixel Depth Offset settings then you cannot use dynamic shadowing. Turn off **cast dynamic shadows** on your landscape. If you need the landscape to still cast shadows you can instead add a shadow pass offset to your landscape that is greater than the pdo offset amount.

You can turn on **Contact Shadows** in the directional light to get detail shadows if you are using pixel depth offset.

From the FAQ https://github.com/Ryan-DowlingSoka/ReliefMappingWiki/wiki/Frequently-Asked-Questions#does-this-plugin-support-shadows

**Does this plugin support shadows?**
Like all relief mapping systems, (without substantial changes and extensive cost) cascaded, raytraced, or virtual shadows are not supported. Cone-step shadows can be implemented directly in the shader, but due to their many limitations I have not implemented them in my material functions. This is mostly because they are limited to a fixed number of lights, have no way to prevent over/double shadowing, and are generally flawed.

Contact Shadows are supported from all light types since the depth buffer can be modified. Contact shadows have their own limitations but are fully functional in the engine and are my recommended method for handling shadows with this system.

Remember to turn off Dynamic and Raytraced shadows when using the pixel depth offset feature. Also remember to turn off Affects Distance Field Lighting

**My meshes are turning black.**
You likely are using the Pixel Depth Offset output and dynamic shadowing. This is causing the mesh to intersect its own shadowing. Turn off any non-contact shadows on meshes using the pixel depth offset output in their materials.

**Comment by Mamubai** [comment]
I still don't quite understand, is there a specific operation，Because there are still problems according to the law

**Comment by Mamubai** [comment]
![HighresScreenshot00004](https://github.com/user-attachments/assets/b992137c-6c7c-4340-939f-4635f4921ca8)

**Comment by Ryan-DowlingSoka** [comment]
I don't see the issue with this image. Any issues here look like they might be content issues, such as a wrong color space normal map.
